app/anime/__init__.py
#!/usr/bin/python

from flask import Blueprint

anime_bp = Blueprint('anime_bp', __name__, static_folder='static', template_folder='templates')

from app.anime import routes

app/anime/routes.py
#!/usr/bin/python

from flask import redirect, render_template, session, redirect, url_for, request, jsonify

from app.models import User, Anime, Season, Episode, AnimeBookmark
from app.anime import anime_bp
from app.anime.helpers import bookmark

import logging

@anime_bp.route("/")
def home():
    animes = [ t[0] for t in Anime.query.with_entities(Anime.name).all() ]
    return render_template("anime/index.html", animes=animes)

@anime_bp.route("/<anime>")
def anime(anime):
    try:
        current_user = User.query.filter_by(username=session['username']).first()
        if current_user:
            bookmark = AnimeBookmark.query.filter_by(user_id=current_user.id, anime_name=anime).order_by(AnimeBookmark.updatetime.desc()).first()
            if bookmark:
                return redirect(url_for('anime_bp.episode', anime=anime, season=bookmark.season, episode=bookmark.episode))
    except Exception as e:
        logging.exception('')
    seasons = [ t[0] for t in Season.query.with_entities(Season.name).filter_by(anime_name=anime).all() ]
    return render_template("anime/anime.html", anime=anime, seasons=seasons)

@anime_bp.route("/<anime>/<season>")
def season(anime, season):
    episodes = [ t[0] for t in Episode.query.with_entities(Episode.name).filter_by(anime_name=anime, season_name=season).all() ]
    return render_template("anime/season.html", anime=anime, season=season, episodes=episodes)

@anime_bp.route("/<anime>/<season>/<episode>")
def episode(anime, season, episode):
    path = Episode.query.filter_by(anime_name=anime, season_name=season, name=episode).first().path
    pos = 0
    try:
        current_user = User.query.filter_by(username=session['username']).first()
        if current_user:
            bookmark = AnimeBookmark.query.filter_by(user_id=current_user.id, anime_name=anime, season=season, episode=episode).first()
            if bookmark:
                pos = bookmark.position
    except Exception as e:
        logging.exception('')
    finally:
        return render_template("anime/episode.html", anime=anime, season=season, episode=episode, path=path, t=str(pos))

@anime_bp.route("/register_timestamp", methods=['POST'])
def register_timestamp():
    try:
        current_user = User.query.filter_by(username=session['username']).first()
        if current_user:
            bookmark(request.form.get("anime"), request.form.get("season"), request.form.get("episode"), current_user.id, pos=request.form.get("t"))
    except Exception as e:
        logging.exception('')
    return jsonify(status="ok")

app/anime/templates/anime/anime.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>{{anime}}</title>
	</head>
	<body>
		<h1>{{anime}}</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<ul id="navigation">
			{% for season in seasons %}
			<li><a href="{{ url_for('anime_bp.season', anime=anime, season=season) }}">{{ season }}</a></li>
			{% endfor %}
		</ul>
	</body>
</html>

app/anime/templates/anime/episode.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>{{episode}}</title>
	</head>
	<body>
		<h1>{{episode}}</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<button is='google-cast-button'></button>
		<div style="text-align: center">
			<video controls id="video">
				<source src={{ url_for('anime_bp.static', filename=path, _anchor='t='+t) | replace('%3D', '=') }} type="video/mp4">
			</video>
		</div>
	</body>
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>
        <script type="text/javascript" charset="utf-8">
                window.__onGCastApiAvailable = function(isAvailable){
                    if(! isAvailable){
                        return false;
                    }

                    var castContext = cast.framework.CastContext.getInstance();

                    castContext.setOptions({
                        autoJoinPolicy: chrome.cast.AutoJoinPolicy.ORIGIN_SCOPED,
                        receiverApplicationId: chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID
                    });

                    var stateChanged = cast.framework.CastContextEventType.CAST_STATE_CHANGED;
                    castContext.addEventListener(stateChanged, function(event){
                        var castSession = castContext.getCurrentSession();
                        var media = new chrome.cast.media.MediaInfo('https://www.example.com/my-song.mp3', 'audio/mp3');
                        var request = new chrome.cast.media.LoadRequest(media);

                        castSession && castSession
                            .loadMedia(request)
                            .then(function(){
                                console.log('Success');
                            })
                            .catch(function(error){
                                console.log('Error: ' + error);
                            });
                    });
                };

		function bookmark() {
			var url = "{{ url_for('anime_bp.register_timestamp') }}";
                	var data = {
				anime: "{{anime}}",
				season: "{{season}}",
				episode: "{{episode}}",
				t: document.getElementById('video').currentTime
			};
                	$.post(url, data);
            	}

		video.addEventListener('play', () => {
  			video._updateInterval = setInterval(() => {
    			bookmark();
  			}, 5000);
		}, true);

		video.addEventListener('pause', () => clearInterval(video._updateInterval), true);
        </script>
	<style>
		@media all and (min-width: 320px) and (max-width: 480px) {
			video {
    				width: 100% !important;
    				height: auto !important;
			}
		}
	</style>
</html>

app/anime/templates/anime/index.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>Better Than One Piece Streaming</title>
	</head>
	<body>
		<h1>Better Than One Piece Streaming</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<ul id="navigation">
			{% for anime in animes %}
			<li><a href="{{ url_for('anime_bp.anime', anime=anime) }}">{{ anime }}</a></li>
			{% endfor %}
		</ul>
	</body>
</html>

app/anime/templates/anime/season.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>{{season}}</title>
	</head>
	<body>
		<h1>{{season}}</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<ul id="navigation">
			{% for episode in episodes %}
			<li><a href="{{ url_for('anime_bp.episode', anime=anime, season=season, episode=episode) }}">{{ episode }}</a></li>
			{% endfor %}
		</ul>
	</body>
</html>