app/scans/__init__.py
#!/usr/bin/python

from flask import Blueprint

scans_bp = Blueprint("scans_bp", __name__, static_folder='static', template_folder='templates')

from app.scans import routes

app/scans/routes.py
#!/usr/bin/python

from flask import render_template, session, redirect, url_for

from app.models import User, Manga, Chapter, Page, MangaBookmark
from app.scans import scans_bp
from app.scans.helpers import bookmark

import logging

@scans_bp.route("/")
def home():
    mangas = [t[0] for t in Manga.query.with_entities(Manga.name).all()]
    return render_template("scans/index.html", mangas=mangas)

@scans_bp.route("/<m>")
def manga(m):
    # if a bookmark is present, redirect the user to the last position directly
    try:
        current_user = User.query.filter_by(username=session['username']).first()
        if current_user:
            bookmark = MangaBookmark.query.filter_by(user_id=current_user.id, manga_name=m).first()
            if bookmark:
                return redirect(url_for('scans_bp.page', m=m, c=bookmark.chapter, p=bookmark.page))
    except Exception as e:
        if 'username' not in e.args:
            logging.exception('')
    chapters = [t[0] for t in Chapter.query.with_entities(Chapter.number).filter_by(manga_name=m).all()]
    return render_template("scans/manga.html", m=m, chapters=chapters)

@scans_bp.route("/<m>/<c>")
def chapter(m, c):
    # the bare chapter URL will redirect the user to page 1
    return redirect(url_for('scans_bp.page', m=m, c=int(c), p=1))

@scans_bp.route("/<m>/<c>/<p>")
def page(m, c, p):
    c = int(c)
    p = int(p)
    chapters = [t[0] for t in Chapter.query.with_entities(Chapter.number).filter_by(manga_name=m).all()]
    pages = [t[0] for t in Page.query.with_entities(Page.number).filter_by(manga_name=m, chapter_number=c).all()]

    if p > len(pages):
        return redirect(url_for('scans_bp.page', m=m, c=c+1, p=1))
    elif p < 1:
        prev_chap = Chapter.query.filter_by(number=c-1).first()
        last_page_number = [t[0] for t in Page.query.with_entities(Page.number).filter_by(manga_name=m, chapter_number=prev_chap.number).all()][-1]
        return redirect(url_for('scans_bp.page', m=m, c=prev_chap.number, p=last_page_number))

    path = Page.query.filter_by(manga_name=m, chapter_number=c, number=p).first().path

    try:
        current_user = User.query.filter_by(username=session['username']).first()
        if current_user:
            bookmark(m, c, p, current_user.id)
    except Exception as e:
        if 'username' not in e.args:
            logging.exception('')
    finally:
        return render_template("scans/page.html", m=m, chapters=chapters, pages=pages, c=c, p=p, path=path)

app/scans/templates/scans/index.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>Better Than Japscan 2</title>
	</head>
	<body>
		<h1>Better Than Japscan 2</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<ul id="navigation">
			{% for manga in mangas %}
			<li><a href="{{ url_for('scans_bp.manga', m=manga) }}">{{ manga }}</a></li>
			{% endfor %}
		</ul>
	</body>
</html>

app/scans/templates/scans/manga.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>{{m}}</title>
	</head>
	<body>
		<h1>{{m}}</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<ul id="navigation">
			{% for chapter in chapters %}
			<li><a href="{{ url_for('scans_bp.page', m=m, c=chapter, p=1) }}">{{ chapter }}</a></li>
			{% endfor %}
		</ul>
	</body>
</html>

app/scans/templates/scans/page.html
<html>
	<head>
		<meta name="viewport" content="width=device-width">
		<title>{{m}} {{c}}</title>
	</head>
	<body>
		<h1>{{m}} {{c}}</h1>
		<a href="{{ url_for('home_bp.home')}}">Menu</a>
		<div id="navigation">
			<a href="{{ url_for('scans_bp.page', m=m, c=c-1, p=1) }}">chap -1</a>
			<a href="{{ url_for('scans_bp.page', m=m, c=c+1, p=1) }}">chap +1</a>
			<select name="listchapters" onchange="location = this.value;">Chapters
            			{% for select_chapter in chapters %}
               			<option {% if select_chapter == c %}selected = "selected"{% endif %} value="{{ url_for('scans_bp.page', m=m, c=select_chapter, p=1) }}">{{select_chapter}}</option>
            			{% endfor %}
         		</select>
			<select name="listpages" onchange="location = this.value;">Pages
            			{% for select_page in pages %}
				<option {% if select_page == p %} selected = "selected" {% endif %} value="{{ url_for('scans_bp.page', m=m, c=c, p=select_page) }}">{{select_page}}</option>
            			{% endfor %}
         		</select>
			<a href="{{ url_for('scans_bp.page', m=m, c=c, p=p-1) }}">page -1</a>
			<a href="{{ url_for('scans_bp.page', m=m, c=c, p=p+1) }}">page +1</a>
		</div>
		<div style="text-align: center">
			<a href="{{ url_for('scans_bp.page', m=m, c=c, p=p+1) }}">
				<img src="{{ url_for('scans_bp.static', filename=path) }}" align="center" style="max-width:100%">
			</a>
		</div>
	</body>
	<script>
		window.addEventListener("keydown", function (event) {
			if(event.defaultPrevented) {
				return;
			}
			switch (event.key) {
				case "ArrowLeft":
				case "h":
					document.location.href="{{ url_for('scans_bp.page', m=m, c=c, p=p-1) }}"
					break;
				case "l":
				case "ArrowRight":
					document.location.href="{{ url_for('scans_bp.page', m=m, c=c, p=p+1) }}"
					break;
				case "k":
				case "ArrowUp":
                  			document.scrollingElement.scrollTop -= 100
                  			break;
				case "j":
               			case "ArrowDown":
					document.scrollingElement.scrollTop += 100
					break;
			}
			event.preventDefault();
		}, true);
	</script>
</html>